services:
  - name: Demo Service 1
    url: https://example.com

  - name: Demo Service 2
    group: service2
    url: https://example.com

  - name: Demo Service 3
    group: service3
    url: https://example.com

  - name: Demo Service
    group: restOfServices
    url: https://example.com

  - name: Demo Service
    group: restOfServices
    url: https://example.com

  - name: Demo Service
    group: restOfServices
    url: https://example.com

  - name: Demo Service
    group: restOfServices
    url: https://example.com

  - name: Demo Service
    group: restOfServices
    url: https://example.com

  - name: Demo Service
    group: restOfServices
    url: https://example.com

  - name: Demo Service
    group: restOfServices
    url: https://example.com

  - name: Demo Service
    group: restOfServices
    url: https://example.com

  - name: Demo Service
    group: restOfServices
    url: https://example.com

  - name: Demo Service
    group: restOfServices
    url: https://example.com

  - name: Demo Service
    group: restOfServices
    url: https://example.com

  - name: Demo Service
    group: restOfServices
    url: https://example.com

  - name: Demo Service
    group: restOfServices
    url: https://example.com

  - name: Demo Service
    group: restOfServices
    url: https://example.com

  - name: Demo Service
    group: restOfServices
    url: https://example.com

  - name: Demo Service
    group: restOfServices
    url: https://example.com

  - name: Demo Service
    group: restOfServices
    url: https://example.com

  - name: Forbidden Demo Service
    group: forbiddengroup
    url: https://example.com
