name: build & lint

on:
  push:
    branches: [ "develop" ]
  pull_request:
    types: [ "opened" ]

jobs:
  base:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: pnpm run build && pnpm run lint
